# -*- coding: utf-8 -*-
"""Plot graphs mô tả variability của 1 data set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKDGkA7owvk2jMnUp9a0a2NTYlGOrr5E

#**Plot graphs mô tả variability của 1 data set sử dụng sublpots**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# two different arrays
x = np.array([2,3,5,6]) # giả định các data set của mình có 4 phần tử
y = np.array([-8,-7,15,16])

# needed for the graph below
my_range = np.arange(4) # parameter của arange xác định bằng số lượng phần tử của dataset (=len(x))tương ứng với 4 vị trí trên trục hoành; nếu data set có n phần tử thì my_range = np.arange(n)

# their respective means
mean_x = np.mean(x)
mean_y = np.mean(y)

fig, axs = plt.subplots(1,2, sharey=True)
axs[0].stem(my_range, x, label='x values', bottom=mean_x)
axs[1].stem(my_range, y, label='y values', bottom=mean_y)
legend_x = axs[0].legend(loc='upper right')
legend_y = axs[1].legend(loc='lower right')

plt.show()

len(x)